export const Users = [
    {
        id:1,
        name: "Pascal Yennyuygha",
        username: "Pascal_1",
        email: "yennyuyghapascal@gmail.com",
        contact: "671772223",
        gender: "Male",
        speciality: "Software Engineering",
        profilePicture: "assets/persons/friend1.jpg",
    },
    {
        id:2,
        name: "Larrien Nya'ah Sa'am",
        username: "Larrien_2",
        email: "larrien@gmail.com",
        contact: "650814245",
        gender: "Male",
        speciality: "Software Engineering, Artificial intelligence",
        profilePicture: "assets/persons/friends2.jpg",
    },
    {
        id:3,
        name: "Nalova Ndive Lyonga",
        username: "nalova_3",
        email: "nalovandive@gmail.com",
        contact: "671969433",
        gender: "Female",
        speciality: "Information Communication Technology",
        profilePicture: "assets/persons/friends3.jpg",
    },
    {
        id:4,
        name: "Ndashi Kelly Ake",
        username: "Ndashi_4",
        email: "ndashikelly@gmail.com",
        contact: "671845397",
        gender: "Female",
        speciality: "Software Engineering",
        profilePicture: "assets/persons/friends4.jpg",
    },
    {
        id:5,
        name: "Bradley Atsimbom Nshom",
        username: "Bradley_5",
        email: "atsimbombradley@gmail.com",
        contact: "651728212",
        gender: "Male",
        speciality: "Data Science",
        profilePicture: "assets/persons/friends5.jpg",
    },
    {
        id:6,
        name: "Joel Fomena Tsatsop Valdes",
        username: "Joel_6",
        email: "joelfomena@gmail.com",
        contact: "681208904",
        gender: "Male",
        speciality: "Computer Science",
        profilePicture: "assets/persons/friends6.jpg",
    //profilePicture: "/assets/person/personno.jpg"
    },
]
export const Posts = [
    {
        userId:3,
        id: 1,
        tittle: "N & N Take away. The beauty of ordering from a reliable source",
        body: " We offer reliable services with customer satisfaction as our top priority. Our stratergy depends not solely on our marketable skills but on knowing someone who knows another who knew another",
        photo: "assets/posts/post1.jpg",
        date: "5 mins ago",
        like: "100",
        comment: "70",
    },
    {
        userId:1,
        id: 2,
        tittle: "The future of Technology",
        body: " We offer reliable services with customer satisfaction as our top priority. Our stratergy depends not solely on our marketable skills but on knowing someone who knows another who knew another",
        photo: "assets/posts/post2.jpg",
        date: "5 mins ago",
        like: "1000",
        comment: "50",
    },
    {
        userId:2,
        id: 3,
        tittle: "Learn To Code with frameworks",
        body: " We offer reliable services with customer satisfaction as our top priority. Our stratergy depends not solely on our marketable skills but on knowing someone who knows another who knew another",
        photo: "assets/posts/post3.jpg",
        date: "5 mins ago",
        like: "80",
        comment: "90",
    },
    {
        userId:4,
        id: 4,
        tittle: "N & N Take away. The beauty of ordering from a reliable source",
        body: " We offer reliable services with customer satisfaction as our top priority. Our stratergy depends not solely on our marketable skills but on knowing someone who knows another who knew another",
        photo: "assets/posts/post4.jpg",
        date: "5 mins ago",
        like: "100",
        comment: "70",
    },
    {
        userId: 5,
        id: 5,
        tittle: "N & N Take away. The beauty of ordering from a reliable source",
        body: " We offer reliable services with customer satisfaction as our top priority. Our stratergy depends not solely on our marketable skills but on knowing someone who knows another who knew another",
        photo: "assets/posts/post5.jpg",
        date: "5 mins ago",
        like: "100",
        comment: "70",
    },
    {
        userId: 6,
        id: 6,
        tittle: "N & N Take away. The beauty of ordering from a reliable source",
        body: " We offer reliable services with customer satisfaction as our top priority. Our stratergy depends not solely on our marketable skills but on knowing someone who knows another who knew another",
        photo: "assets/posts/post6.jpg",
        date: "5 mins ago",
        like: "100",
        comment: "70",
    },
];

export const UsersOnline = [
    {
        id:1,
        name: "Daniel Bronze",
        username: "Daniel_11",
        email: "daniel@gmail.com",
        profilePicture: "/assets/persons/friends1.jpg",
    },
    {
        id:1,
        name: "Gift Fomo",
        username: "Gift_99",
        email: "gift11@gmail.com",
        profilePicture: "/assets/persons/friends2.jpg",
    },{
        id:1,
        name: "Clarkson Berinyuy ",
        username: "Clarkson",
        email: "clarkson@gmail.com",
        profilePicture: "/assets/persons/friends3.jpg",
    },
    {
        id:1,
        name: "Denison Verbee",
        username: "Denison",
        email: "verbee@gmail.com",
        profilePicture: "/assets/persons/friends4.jpg",
    },{
        id:1,
        name: "McCathy Lisbon",
        username: "Lisbon_Mc",
        email: "lisbon@gmail.com",
        profilePicture: "/assets/persons/friends5.jpg",
    },
    {
        id:1,
        name: "Lyn Bevert",
        username: "Lyn_132",
        email: "bevert@gmail.com",
        profilePicture: "/assets/persons/friends6.jpg",
    },{
        id:1,
        name: "Bless Kliint",
        username: "Blazzo",
        email: "bless@gmail.com",
        profilePicture: "/assets/persons/friends7.jpg",
    },
]